### PR TITLE
Make the codebase buildable on Rustc 1.34 (Debian stable version)

### PR DESCRIPTION
**Pull request by laarmen**
I needed to be able to build on an older version of Rustc, the one shipped in the Debian Stable repositories. The changes are relatively minor. Sadly, I wasn't able to properly separate the rustfmt change in the example from the proper changes, but the commit-per-commit view should be easier to deal with.

### CODE REVIEW

**Comment by uccidibuti** [comment]
Ok thanks for your contributions, I want to replace rebpf-sys with https://github.com/alexforster/libbpf-sys this weekend, I hope this won't cause you any problems..

**Comment by laarmen** [comment]
You just want to replace the rebpf_sys crate, right? If so, this shouldn't
cause much trouble, I'm more focused on the BPF kernel code for now :)

I might have some more stuff for you over the next few days, depending on
my work load :)

**Comment by uccidibuti** [comment]
Yes, I have replaced rebpf-sys with libbpf-sys let me know if you have some problems, I will try to create a docker file to build bpf programs without bpf dependency..

**Comment by laarmen** [comment]
The only thing I need to make sure of is that the new dependency builds on
1.34. If not, well... I guess I'll know what I'll be doing next 😉

Le sam. 18 avr. 2020 à 16:18, Lorenzo Vannucci <notifications@github.com> a
écrit :

**Pull request merged**
